import React from 'react'
import { storiesOf } from '@storybook/react'
import { PageBuilder } from '../../PageBuilder'

const htmlInline = `<div data-content-type=\"row\" data-appearance=\"full-width\" data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-element=\"main\" style=\"justify-content: center; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; min-height: 200px; margin: 0px; padding: 10px;\"><div class=\"row-full-width-inner\" data-element=\"inner\"><div data-content-type=\"buttons\" data-appearance=\"inline\" data-same-width=\"false\" data-element=\"main\" style=\"border-style: none; border-width: 1px; border-radius: 0px; margin: 0px; padding: 10px 10px 0px;\"><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><div class=\"pagebuilder-button-primary\" data-element=\"empty_link\" style=\"text-align: center;\"><span data-element=\"link_text\">Primary Button</span></div></div><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><div class=\"pagebuilder-button-secondary\" data-element=\"empty_link\" style=\"text-align: center;\"><span data-element=\"link_text\">Secondary Button</span></div></div><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><a class=\"pagebuilder-button-link\" href=\"https://magento.com\" target=\"_blank\" data-link-type=\"default\" data-element=\"link\" style=\"text-align: center;\"><span data-element=\"link_text\">Magento.com&nbsp;</span></a></div></div></div></div>`
const htmlStacked = `<div data-content-type=\"row\" data-appearance=\"full-width\" data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-element=\"main\" style=\"justify-content: center; display: flex; flex-direction: column; background-position: left top; background-size: cover; background-repeat: no-repeat; background-attachment: scroll; border-style: none; border-width: 1px; border-radius: 0px; min-height: 200px; margin: 0px; padding: 10px;\"><div class=\"row-full-width-inner\" data-element=\"inner\"><div data-content-type=\"buttons\" data-appearance=\"stacked\" data-same-width=\"true\" data-element=\"main\" style=\"border-style: none; border-width: 1px; border-radius: 0px; display: flex; margin: 0px; padding: 10px 10px 0px; flex-direction: column;\"><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><div class=\"pagebuilder-button-primary\" data-element=\"empty_link\" style=\"text-align: center;\"><span data-element=\"link_text\">Primary Button</span></div></div><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><div class=\"pagebuilder-button-secondary\" data-element=\"empty_link\" style=\"text-align: center;\"><span data-element=\"link_text\">Secondary Button</span></div></div><div data-content-type=\"button-item\" data-appearance=\"default\" data-element=\"main\" style=\"display: inline-block;\"><a class=\"pagebuilder-button-link\" href=\"https://magento.com\" target=\"_blank\" data-link-type=\"default\" data-element=\"link\" style=\"text-align: center;\"><span data-element=\"link_text\">Magento.com&nbsp;</span></a></div></div></div></div>`
storiesOf('📦 Components/PageBuilder/Buttons', module)
    .add('Inline', () => <PageBuilder html={htmlInline} />)
    .add('Stacked', () => <PageBuilder html={htmlStacked} />)
